import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from './login';
import { useState } from 'react';

export default function Home() {

  const [session, setSession] = useState(null);

  return (
    <div>
      <Head>
        <title>Wake Smiles App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Login/>
      </div>
    </div>
  )
}
